### ISSUE TITLE
Error: webpack.optimize.UglifyJsPlugin has been removed

### ISSUE THREAD

**Issue by McPringle** [gyulavoros/kotlin-todomvc#1]
After i cloned this repo I started the backend and the frontend as shown in the README file:

```bash
$ ./gradlew backend:run
$ ./gradlew -t frontend:run
```

While the backend runs fine, the frontend raises an exception:

```
> Task :frontend:webpack-run 
webpack-dev-server exited with exit code 1, see /Users/mcpringle/GitHub/other/kotlin-todomvc/frontend/build/logs/webpack-dev-server.log
/Users/mcpringle/GitHub/other/kotlin-todomvc/frontend/build/node_modules/webpack/lib/webpack.js:162
                        throw new RemovedPluginError(errorMessage);
                        ^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (/Users/mcpringle/GitHub/other/kotlin-todomvc/frontend/build/node_modules/webpack/lib/webpack.js:162:10)
    at Object.<anonymous> (/Users/mcpringle/GitHub/other/kotlin-todomvc/frontend/build/webpack.config.js:42:44)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mcpringle/GitHub/other/kotlin-todomvc/frontend/build/webpack-dev-server-run.js:22:14)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:webpack-run'.
> webpack-dev-server startup failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
16 actionable tasks: 2 executed, 14 up-to-date
```

I run macOS High Sierra 10.13.3 and tried Java 8u152 and 9.0.4.

**Comment by gyulavoros** [comment]
I cannot reproduce. Can you take a look at the `kotlin-todomvc/frontend/build/node_modules/webpack/package.json` file and check the version number? For me it's `webpack@3.10.0` and it works fine, but it seems that in webpack 4, [things have changed](https://stackoverflow.com/questions/49053215/webpack-4-how-to-configure-minimize).
